services:
  backend:
    build:
      context: .
      args:
        BUILD_JOBS: 6
      target: builder
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    command: sleep infinity
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - NS_MARIADB_USER=${NS_MARIADB_USER}
      - NS_MARIADB_PASSWORD=${NS_MARIADB_PASSWORD}
      - NS_MARIADB_DATABASE=${NS_MARIADB_DATABASE}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - FRONTEND_URL=${FRONTEND_URL}
      - BACKEND_URL=${BACKEND_URL}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    depends_on:
      - db
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, video]
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${NS_MARIADB_DATABASE}
      - MYSQL_USER=${NS_MARIADB_USER}
      - MYSQL_PASSWORD=${NS_MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_NOTIFY_WEBHOOK_ENABLE_1=on
      - MINIO_NOTIFY_WEBHOOK_ENDPOINT_1=http://backend:8080/webhooks/minio
      - MINIO_API_CORS_ALLOW_ORIGIN=http://localhost:4200
    ports:
      - "9000:9000" # API用
      - "9001:9001" # コンソール用
    volumes:
      - minio_data:/data
  minio-init:
    image: minio/mc:latest
    container_name: minio-init
    depends_on:
      - minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./docker/minio/init.sh:/init.sh
    entrypoint: /bin/sh -c "chmod +x /init.sh && /init.sh"
volumes:
  db_data:
  redis_data:
  minio_data:
