CREATE TABLE IF NOT EXISTS external_video_statistics (
	video_id VARCHAR(255) PRIMARY KEY,
	provider VARCHAR(32) NOT NULL,
	view_count BIGINT UNSIGNED,
	like_count BIGINT UNSIGNED,
	comment_count BIGINT UNSIGNED,
	synced_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (video_id) REFERENCES videos(video_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS external_video_metadata (
	video_id VARCHAR(255) PRIMARY KEY,
	provider VARCHAR(32) NOT NULL,
	metadata JSON NOT NULL,
	synced_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (video_id) REFERENCES videos(video_id) ON DELETE CASCADE
);
